node {
      stage ('Checkout') {
            git 'https://github.com/Praveenreddy003/bazel.git'
         ls
      }
     
    stage('Bazel build') {
      
        sh '''
        ls
        cd examples/cpp
        bazel build hello-world
        '''
    }
  }
