pipeline {
  agent any
  stages {
      stage ('Checkout') {
       steps{
            checkout scm 
      }
      }
    stage('Bazel Build') {
      steps {
        sh 'bazel build hello-word'
      }
    }
  }
}
